apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - /etc/prometheus/alerts.yml

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

      - job_name: kube-state-metrics
        static_configs:
          - targets: ["kube-state-metrics.monitoring.svc.cluster.local:8080"]

      - job_name: node-exporter
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: [monitoring]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: node-exporter
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics

  alerts.yml: |
    groups:
      - name: capstone-app
        rules:
          - alert: CapstoneAppDown
            expr: up{job="kubernetes-pods", kubernetes_namespace="capstone-app"} == 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: Capstone app pod not scrapeable
              description: Prometheus cannot scrape the capstone-app pods for 2 minutes.

          - alert: CapstoneHighRequestRate
            expr: rate(app_requests_total{kubernetes_namespace="capstone-app"}[5m]) > 50
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: Unusually high request rate on capstone app

          - alert: NodeHighCPU
            expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle",job="node-exporter"}[5m])) * 100) > 85
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: Node CPU above 85%
